mysql.url=jdbc:mysql://localhost:3306/hzcu_mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
mysql.username=root
mysql.password=123456
mysql.driver=com.mysql.cj.jdbc.Driver

mongodb.uri=mongodb://root:123456@localhost:27017/hzcu_mongo?authSource=admin
mongodb.database=hzcu_mongo
